services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db
    
  db:
    # pgvectorが最初からインストールされているイメージを使用
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: